# Generated by Django 3.2.3 on 2021-05-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210519_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default=1, max_length=64),
        ),
    ]
